In [1]:
import pandas as pd
from io import StringIO

In [35]:
file_path = '/Volumes/WD_BLACK/hg38_files/UOK342-YAP1-all.mat'  # Path to the file

# Read the contents of the file
with open(file_path, 'r') as file:
    lines = file.readlines()

# Check if the first line starts with "chr"
if lines and not lines[0].startswith('chr'):
    # Remove the first line
    lines = lines[1:]

# Write the updated contents back to the file
with open(file_path, 'w') as file:
    file.writelines(lines)

In [41]:

#test if data_transfer is done
df = pd.read_csv('/Volumes/WD_BLACK/hg38_files/UOK342-YAP1-all.mat', sep="\t",header=None)
df

,0,1,2,3,4,5,6,7,8,9,...,1796,1797,1798,1799,1800,1801,1802,1803,1804,1805
0,chr1,597605,598048,UOK121-H3K9me3-rep2_S29.macs_peak_1,32.0,.,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,chr1,600262,600534,UOK121-H3K9me3-rep2_S29.macs_peak_2,32.0,.,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,chr1,788709,789095,UOK121-H3K9me3-rep2_S29.macs_peak_3,90.0,.,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,chr1,790091,790363,UOK121-H3K9me3-rep2_S29.macs_peak_4,24.0,.,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.3,0.0,0.0
4,chr1,948493,948765,UOK121-H3K9me3-rep2_S29.macs_peak_5,13.0,.,0.0,0.0,6.3,7.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371548,chrY,56830020,56830403,UOK121-H3K9me3-rep2_S29.macs_peak_371549,38.0,.,5.0,5.0,5.0,5.0,...,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,5.7,3.0
371549,chrY,56832978,56833427,UOK121-H3K9me3-rep2_S29.macs_peak_371550,101.0,.,9.0,9.0,9.0,9.0,...,6.0,6.0,6.0,6.0,5.0,1.0,1.0,1.0,1.0,1.2
371550,chrY,56833669,56833941,UOK121-H3K9me3-rep2_S29.macs_peak_371551,36.0,.,2.0,2.0,2.0,2.0,...,26.0,26.0,26.0,26.0,20.5,15.0,15.0,15.0,15.0,18.0
371551,chrY,56835608,56835989,UOK121-H3K9me3-rep2_S29.macs_peak_371552,75.0,.,8.4,8.0,8.0,8.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
371552,chrY,56856506,56856778,UOK121-H3K9me3-rep2_S29.macs_peak_371553,16.0,.,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [54]:
# Sort the DataFrame based on column number 4
df1 = df
df1.sort_values(by=df1.columns[900],ascending=False, inplace=True)
df1.head(10)

,0,1,2,3,4,5,6,7,8,9,...,1796,1797,1798,1799,1800,1801,1802,1803,1804,1805
209668,chr3,93470319,93470832,UOK121-H3K9me3-rep2_S29.macs_peak_209669,25412.0,.,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5,1.0,1.0
33847,chr10,50425463,50425901,UOK121-H3K9me3-rep2_S29.macs_peak_33848,2423.0,.,0.0,0.6,3.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
356752,chrUn_KI270438v1,109192,109877,UOK121-H3K9me3-rep2_S29.macs_peak_356753,1813.0,.,19.0,28.6,43.0,43.0,...,434.0,312.0,129.0,129.0,129.0,129.0,77.4,0.0,NaN,NaN
33094,chr10,41859663,41860329,UOK121-H3K9me3-rep2_S29.macs_peak_33095,250.0,.,4.2,7.0,7.0,7.0,...,3.6,4.0,4.0,4.0,4.0,10.6,15.0,15.0,15.0,15.0
356799,chrUn_KI270467v1,1007,1523,UOK121-H3K9me3-rep2_S29.macs_peak_356800,1257.0,.,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
189397,chr21,7258755,7259036,UOK121-H3K9me3-rep2_S29.macs_peak_189398,226.0,.,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
356755,chrUn_KI270438v1,111909,112505,UOK121-H3K9me3-rep2_S29.macs_peak_356756,1011.0,.,251.0,251.0,251.0,251.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119449,chr16,46390291,46390965,UOK121-H3K9me3-rep2_S29.macs_peak_119450,1374.0,.,117.0,117.0,137.0,142.0,...,12.0,12.0,7.2,6.0,6.0,6.0,6.0,2.0,1.0,1.0
356753,chrUn_KI270438v1,110330,110605,UOK121-H3K9me3-rep2_S29.macs_peak_356754,108.0,.,10.0,10.0,10.0,7.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
146313,chr19,17665491,17665933,UOK121-H3K9me3-rep2_S29.macs_peak_146314,124.0,.,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [57]:
df1.iloc[1:10,900:910]

,900,901,902,903,904,905,906,907,908,909
33847,3323.0,3323.0,3948.6,6451.0,6451.0,6451.0,6451.0,5787.4,3133.0,3133.0
356752,1182.0,1182.0,836.4,318.0,318.0,318.0,318.0,562.4,929.0,929.0
33094,1082.0,1050.8,1030.0,1030.0,1030.0,1030.0,424.0,20.0,20.0,20.0
356799,1059.0,1059.0,1059.0,1059.0,1096.5,1134.0,1134.0,1134.0,1134.0,596.5
189397,991.0,496.5,2.0,2.0,2.0,2.0,9.5,17.0,17.0,17.0
356755,752.3,707.0,707.0,707.0,707.0,401.1,270.0,270.0,270.0,270.0
119449,663.0,663.0,663.0,466.2,417.0,417.0,417.0,417.0,863.4,975.0
356753,661.0,661.0,661.0,661.0,657.5,656.0,656.0,656.0,656.0,646.2
146313,635.0,635.0,635.0,635.0,712.2,1021.0,1021.0,1021.0,1021.0,894.0

In [61]:
top_1000_peaks = df1.head(1000)

# Write the top 1000 peaks to a new file
top_1000_peaks.to_csv("/Volumes/WD_BLACK/hg38_files/top1000.csv",index=False)